name: e2e

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.21.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Setup Kubernetes
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          version: v0.20.0
          node_image: kindest/node:v1.28.0
          cluster_name: kind
      - name: Install
        run: make install
      - name: Push module
        run: |
          timoni mod push ./examples/minimal oci://localhost:5000/minimal -v 1.0.0 --latest
      - name: Install module
        run: |
          timoni -n test apply nginx oci://localhost:5000/minimal
      - name: List modules
        run: |
          timoni list -A
      - name: Upgrade module
        run: |
          echo 'values: message: "e2e"' | timoni -n test apply nginx oci://localhost:5000/minimal -v 1.0.0 -f-
      - name: Inspect module
        run: |
          timoni -n test inspect resources nginx
          timoni -n test inspect module nginx
          timoni -n test inspect values nginx
      - name: Status module
        run: |
          timoni -n test status nginx
      - name: Uninstall module
        run: |
          timoni -n test delete nginx --wait
